# Generated by Django 5.2.3 on 2025-07-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='color_scheme',
            field=models.CharField(choices=[('blue', 'Professional Blue'), ('green', 'Success Green'), ('purple', 'Creative Purple'), ('red', 'Bold Red'), ('gray', 'Classic Gray'), ('navy', 'Navy Blue'), ('teal', 'Modern Teal'), ('custom', 'Custom')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='custom_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='keywords_matched',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resume',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimalist', 'Minimalist'), ('professional', 'Professional'), ('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare')], default='modern', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
