# Generated by Django 5.2.3 on 2025-07-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_resume_ai_suggestions_resume_ats_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
