# Generated by Django 5.2.3 on 2025-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_resume_github_url_resume_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='professional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
